name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main
    paths:
      - 'Code.js'
      - 'appsscript.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Configure clasp authentication
        run: |
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Check clasp status (optional debug)
        run: clasp status

      - name: Push to Google Apps Script
        run: clasp push
